config/routes.rb
PrimalAuth::Application.routes.draw do

  get 'dashboard' => "dashboard#index"

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'user/edit' => 'users#edit', :as => :edit_current_user
  put 'signup' => 'users#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create', :as => :new_session

  get 'logout' => 'sessions#destroy'

  resources :password_resets, :only => [:new, :create, :edit, :update]

  get 'confirm/:id' => 'confirmations#confirm', :as => :confirmation
  get 'confirmation_needed' => 'confirmations#confirmation_needed'

  match "auth/:provider/callback" => "omniauth#create"
  match 'auth/failure' => 'omniauth#failure'

  root :to => 'home#index'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :login_required

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    # NB: this redirect is OK as we don't want to disclose that the user doesn't exist (if it doesn't)
    redirect_to root_url, :notice => "Email sent with password reset instructions."
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])

    # we should require the password to be present (unlike when editting user profile)
    unless params[:user][:password].present?
      @user.errors.add(:password, 'must be present')
      render :edit and return
    end

    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(params[:user])
      redirect_to root_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end
end

app/views/password_resets/edit.html.erb
<% title "Password reset" %>

<h1>Reset Password</h1>

<%= form_for @user, :url => password_reset_path(params[:id]) do |f| %>
  <%= render "shared/error_messages", :target => @user %>

  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>

  <p><%= f.submit "Update Password" %></p>
<% end %>

app/views/password_resets/new.html.erb
<% title "Password reset" %>

<%= form_tag password_resets_path, :method => :post do %>
  <p>
    <%= label_tag :email, 'Email' %><br />
    <%= text_field_tag :email %>
  </p>

  <p><%= submit_tag "Reset password" %></p>
<% end %>

<p><%= link_to 'Back', login_path  %> | <%= link_to 'Home', root_path  %></p>