config/routes.rb
PrimalAuth::Application.routes.draw do

  get 'dashboard' => "dashboard#index"

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'user/edit' => 'users#edit', :as => :edit_current_user
  put 'signup' => 'users#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create', :as => :new_session

  get 'logout' => 'sessions#destroy'

  resources :password_resets, :only => [:new, :create, :edit, :update]

  get 'confirm/:id' => 'confirmations#confirm', :as => :confirmation
  get 'confirmation_needed' => 'confirmations#confirmation_needed'

  match "auth/:provider/callback" => "omniauth#create"
  match 'auth/failure' => 'omniauth#failure'

  root :to => 'home#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  password_hash          :string(255)
#  password_salt          :string(255)
#  remember_token         :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  last_login_at          :datetime
#  last_logout_at         :datetime
#  last_activity_at       :datetime
#  login_count            :integer         default(0)
#  last_login_ip          :string(255)
#  provider               :string(255)
#  uid                    :string(255)
#

class User < ActiveRecord::Base
  include Extensions::Authentication

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :login_required, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to :action => :confirmation_needed, :controller => :confirmations
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
    render_edit_template
  end

  def update
    @user = current_user

    if params[:user][:email].present? && params[:user][:email] != @user.email
      @user.confirmed_at = nil
      @user.attributes = params[:user]
      @user.send_confirmation_instructions

      @user.logout(cookies)
      reset_session

      redirect_to :action => :confirmation_needed, :controller => :confirmations
      return
    end

    if @user.update_attributes(params[:user])
      redirect_to dashboard_url, :notice => "Your profile has been updated."
    else
      render_edit_template
    end
  end

private

  def render_edit_template
    params['oauth'].present? ? render('edit_with_oauth') : render('edit')
  end
end

app/views/users/_email.html.erb
    <p>
      <%= f.label :email, "Email" %><br />
      <%= f.text_field :email %>
    </p>

app/views/users/_form.html.erb
<div id="signup_form">
  <%= form_for @user, :url => signup_path do |f| %>
    <%= render "shared/error_messages", :target => @user %>

    <p>
      <%= f.label :name, "Name" %><br />
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :email, "Email" %><br />
      <%= f.text_field :email %>
    </p>

    <p>
      <%= f.label :password, "Password" %><br />
      <%= f.password_field :password %>
    </p>

    <p>
      <%= f.label :password_confirmation, "Confirm Password" %><br />
      <%= f.password_field :password_confirmation %>
    </p>

    <p><%= f.submit (@user.new_record? ? "Sign up" : "Update") %></p>
  <% end %>
</div>

app/views/users/_name.html.erb
    <p>
      <%= f.label :name, "Name" %><br />
      <%= f.text_field :name %>
    </p>

app/views/users/_password.html.erb
    <p>
      <%= f.label :password, "Password" %><br />
      <%= f.password_field :password %>
    </p>

app/views/users/_password_confirmation.html.erb
    <p>
      <%= f.label :password_confirmation, "Confirm Password" %><br />
      <%= f.password_field :password_confirmation %>
    </p>

app/views/users/edit.html.erb
<% title "Update Profile" %>

<%= render 'form' %>

<p><%= link_to 'Dashboard', dashboard_path  %></p>

app/views/users/edit_with_oauth.html.erb
<% title "Update Profile" %>

<div id="signup_form">
  <%= form_for @user, :url => signup_path do |f| %>
    <%= render "shared/error_messages", :target => @user %>

    <%= render "name", :f => f %>
    <%= render "email", :f => f %>

    <input type="hidden" name="oauth" value="1" />

    <p><%= f.submit "Update" %></p>
  <% end %>
</div>

<p><%= link_to 'Dashboard', dashboard_path  %></p>

app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<%= render 'form' %>

<p><%= link_to 'Home', root_path  %></p>