config/routes.rb
PrimalAuth::Application.routes.draw do

  get 'dashboard' => "dashboard#index"

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'user/edit' => 'users#edit', :as => :edit_current_user
  put 'signup' => 'users#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create', :as => :new_session

  get 'logout' => 'sessions#destroy'

  resources :password_resets, :only => [:new, :create, :edit, :update]

  get 'confirm/:id' => 'confirmations#confirm', :as => :confirmation
  get 'confirmation_needed' => 'confirmations#confirmation_needed'

  match "auth/:provider/callback" => "omniauth#create"
  match 'auth/failure' => 'omniauth#failure'

  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) + " – PrimalAuth" : "PrimalAuth" %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>

<body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>

      <% user_navigation do -%>
        <div id="user_nav">
        <% if logged_in? -%>
          Welcome, <%= current_user.name %> •

          <% if current_user.authenticated_with_omniauth? -%>
            <%= link_to 'Edit profile', edit_current_user_path(:oauth => 1) %> •
          <% else -%>
            <%= link_to 'Edit profile', edit_current_user_path %> •
          <% end -%>

          <%= link_to 'Log out', logout_path %>
        <% else -%>
          <%= link_to 'Sign up', signup_path %> or <%= link_to 'Log in', login_path %>
        <% end -%>
        </div>
      <% end -%>

      <%= yield %>
    </div>

    <%= debug params %>
</body>
</html>